	.NEW
	.INSERT	"GEFREQ"
	.INSERT "GEDAT"			; DATA IS IN THIS FILE
	.INSERT "G-MISC"
	.INSERT "G-PARSER"
	.INSERT "G-GLOBALS"
	.INSERT "G-SYNTAX"
	.INSERT "G-VERBS"
	.INSERT "G-ROOMS"
	.INSERT "GESTR"
	.END
